### ISSUE TITLE
Clean Up The Main GUI

### ISSUE THREAD

**Issue by Gocnak** [Gocnak/Botnak#67]
The main GUI has its design from maybe a year ago, it's time we make it simplified and cleaner.

Perhaps move the buttons to a JMenuBar or something, and make the user chat box be skinnier.

(Does the "Chat" button need to exist anymore?)

**Comment by Triscy** [comment]
I'd say the "Chat" button should remain on the new one for more novice users or in those rare cases when you awkwardly need to click a button to send a message due to cats in your lap/other interference. Though I feel renaming it "Send" is better, as that's what it really does.

Speaking of this, being able to change the font/font size would be useful.

**Comment by Gocnak** [comment]
You mean changing the font size and type for the box to type in?

**Comment by Triscy** [comment]
No. I mean, you have an option currently in the settings for font and font size which doesn't work. At least for me. I change it and it does absolutely nothing.

**Comment by Gocnak** [comment]
Oh. Whoops.
