### ISSUE TITLE
Emote issue with v 2.31

### ISSUE THREAD

**Issue by razgrillz** [Gocnak/Botnak#86]
With version 2.31, when going to post emotes, emotes from the client will not show until someone else has posted them in the chat first. Caching (I assume its caching) allows the emotes said in one chat to transfer over into another tab just fine.
[Example](http://puu.sh/i2FR6/c79c4b7a69.png)
[Ex 2. in someone else's chat](http://puu.sh/i2Gw0/7c7b737da2.png)

**Comment by Gocnak** [comment]
Ah, I think you mean just for the Botnak user. When you submit a message, all Twitch sends back is the USERSTATE message, which does not tell what emotes you use in your message. Every other person's messages are sent with IRCv3 tags which tell what emotes are used.

A solution to this would be having the bot follow along, since it can edit the user when it sees you using the emote. It's gonna be wonky like this until Twitch solidifies with IRCv3 and rids TWITCHCLIENT stuff. I can try to recommend to the devs to send something that tells what emotes you used in your message, to make it so that we can know so this annoying error doesn't happen anymore.
