### ISSUE TITLE
Saving Sounds Permission

### ISSUE THREAD

**Issue by Kiwi-1995** [Gocnak/Botnak#90]
Sounds that have a 0 permissions or "everyone" permission can't actually be played by guests. Only mods and the broadcaster.

I have re-added the offending sounds and made sure the permissions were set to everyone and it has not made a difference.

**Comment by Gocnak** [comment]
Try using the "!setsoundperm 0" command, which does not save to settings so you'll have to do it every time you boot Botnak.

I may just hijack this issue to make it the reminder to make it something that gets saved, either in defaults.ini or whatnot.

**Comment by Kiwi-1995** [comment]
!setsoundperm to 0 also does not fix the issue even though the bot reports in chat that it has changed to 0. Is there any debugging I can do that may help the issue get resolved?

**Comment by Gocnak** [comment]
Was the sound added with a sub+ permission? I mean doing "!addsound soundname soundfile.wav" should make it playable for everyone.

If you can, try to tell me the process of how you're testing these sounds and I will try to recreate it.

**Comment by Kiwi-1995** [comment]
I've added the sounds through the GUI not through twitch chat. They are set to everyone. Even manually selected them if the default preset wasn't enough.

**Comment by Gocnak** [comment]
Okay so I've found the issue, it's the Settings GUI sound tree which is broken.

I'm pretty much going to be overhauling this GUI for the release of Botnak 2 Episode 2, which I will start soon.

For now, just use the "!addsound" command found [here](https://docs.google.com/document/d/1aY9ev1mhYN7mMXhYhZ_QCTORvCAy3iGq56vMLZFiiYY/) under "moderator commands" and the sounds should be added and work. Also make sure that you have set the default sounds directory, since the chat command uses that directory to add the sounds.

**Comment by Kiwi-1995** [comment]
Cool. Thanks.

**Comment by Gocnak** [comment]
I'm gonna branch this off as "re-do the sound tree" in another issue report. But the sounds permission will be saved from now on!
