### ISSUE TITLE
Whisper Support

### ISSUE THREAD

**Issue by Gocnak** [Gocnak/Botnak#95]
Add a whisper connection for whispering bot replies of certain commands, such as !setcol and !nameface commands.

**Comment by Chrisazy** [comment]
In order to accomplish this, the bot needs another IRC client to connect to one of the groupchat servers on channel `#jtv` and to send messages to that channel in the form of `\w recipient message follows ...` So it shouldn't be impossible, but the existing PircBot code is all very botnak/twitch specific, so I'm kind of tearing it apart. https://github.com/Chrisazy/Botnak/tree/Whispering
